### ISSUE TITLE
weird OutOfMemoryError?

### ISSUE THREAD

**Issue by YoungjaeKim** [alexkvak/teamcity-slack#47]
Hi.
I changed Slack OAuth Access Token in Administration and it throws TeamCity error when I click Save button.
my server has 50% memory usage (more than 200MB free memory)

TeamCity Diagnostics shows 100MB memory increases after the crisis.

Do you have any idea? 

```
Trace: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at ch.qos.logback.core.pattern.FormattingConverter.write(FormattingConverter.java:40)
	at ch.qos.logback.core.pattern.PatternLayoutBase.writeLoopOnConverters(PatternLayoutBase.java:119)
	at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:149)
	at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:39)
	at ch.qos.logback.core.encoder.LayoutWrappingEncoder.doEncode(LayoutWrappingEncoder.java:134)
	at ch.qos.logback.core.OutputStreamAppender.writeOut(OutputStreamAppender.java:194)
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:219)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:103)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:88)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:48)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:273)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:260)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:442)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:396)
	at ch.qos.logback.classic.Logger.debug(Logger.java:503)
	at com.ullink.slack.simpleslackapi.impl.SlackJSONSessionStatusParser.parse(SlackJSONSessionStatusParser.java:67)
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connectImpl(SlackWebSocketSessionImpl.java:313)
	at com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl.connect(SlackWebSocketSessionImpl.java:285)
	at com.fpd.teamcity.slack.SlackGateway.$anonfun$sessionByConfig$2(SlackGateway.scala:97)
	at com.fpd.teamcity.slack.SlackGateway$$Lambda$1919/892078448.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.Try$.apply(Try.scala:209)
	at com.fpd.teamcity.slack.SlackGateway.sessionByConfig(SlackGateway.scala:97)
	at com.fpd.teamcity.slack.controllers.ConfigController.$anonfun$handle$1(ConfigController.scala:33)
	at com.fpd.teamcity.slack.controllers.ConfigController$$Lambda$2198/1736282298.apply(Unknown Source)
	at scala.Option.map(Option.scala:146)
	at com.fpd.teamcity.slack.controllers.ConfigController.handle(ConfigController.scala:27)
	at com.fpd.teamcity.slack.controllers.SlackController.doHandle(SlackController.scala:17)
```

**Comment by YoungjaeKim** [comment]
The version above was 1.1.7, and I confirmed that 1.1.8 works fine.
