### ISSUE TITLE
"Try it" fails to return

### ISSUE THREAD

**Issue by doctorbigtime** [alexkvak/teamcity-slack#7]
Hi there

After setting up the application and bot, I wanted to test my configuration with "Try it" on a build configuration, the "Sending..." pop up box hangs and the stack trace below is output in teamcity-server.log
Seems to be during compilation of a regex (I used ".\*")
Of note: I am using svn as a repo and it's unclear to me what "branch" means in svn, which is why i used ".\*"

```
ERROR -   jetbrains.buildServer.SERVER - Error java.lang.NullPointerException while processing request: POST '/app/slackIntegration/buildSettingTry.html?id=XXXX', from client X.X.X.X:55244, authenticated as 'xxxx' {id=1} 
java.lang.NullPointerException
        at com.fpd.teamcity.slack.MessageBuilder.$anonfun$compile$9(MessageBuilder.scala:59)
        at scala.Option.map(Option.scala:146)
        at com.fpd.teamcity.slack.MessageBuilder.$anonfun$compile$8(MessageBuilder.scala:59)
        at scala.util.matching.Regex.$anonfun$replaceAllIn$1(Regex.scala:491)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1406)
        at scala.util.matching.Regex.replaceAllIn(Regex.scala:491)
        at com.fpd.teamcity.slack.MessageBuilder.compile(MessageBuilder.scala:56)
        at com.fpd.teamcity.slack.controllers.BuildSettingsTry.$anonfun$handle$4(BuildSettingsTry.scala:31)
        at scala.Option.flatMap(Option.scala:171)
        at com.fpd.teamcity.slack.controllers.BuildSettingsTry.$anonfun$handle$2(BuildSettingsTry.scala:30)
        at scala.Option.flatMap(Option.scala:171)
        at com.fpd.teamcity.slack.controllers.BuildSettingsTry.$anonfun$handle$1(BuildSettingsTry.scala:29)
        at scala.Option.flatMap(Option.scala:171)
        at com.fpd.teamcity.slack.controllers.BuildSettingsTry.handle(BuildSettingsTry.scala:28)
        at com.fpd.teamcity.slack.controllers.SlackController.doHandle(SlackController.scala:17)
        at com.fpd.teamcity.slack.controllers.SlackController.doHandle$(SlackController.scala:15)
        at com.fpd.teamcity.slack.controllers.BuildSettingsTry.doHandle(BuildSettingsTry.scala:14)
        at jetbrains.buildServer.controllers.BaseController.handleRequestInternal(BaseController.java:75)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:147)
        at 
[...]

```

**Comment by alexkvak** [comment]
Thanks for report!
Please try release v1.0.2 in couple of minutes

**Comment by doctorbigtime** [comment]
nice, works fine now.
Thanks!
